import {Dimensions, StyleSheet} from 'react-native';

export const AuthStyle = StyleSheet.create({
  header: {
    width: Dimensions.get('window').width,
    height: 230,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    zIndex: 1,
    marginBottom: 0,
  },
  img: {
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  main: {
    paddingTop: 10,
    marginTop: 10,
    marginHorizontal: 15,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    backgroundColor: '#ffffff',
    height: Dimensions.get('window').height,
    width: 367,
    alignItems: 'center',
    elevation: 10,
  },
  input: {
    marginBottom: 16,
    paddingVertical: 15,
    paddingHorizontal: 15,
    backgroundColor: '#F5F5F5',
    borderRadius: 15,
    borderColor: '#EFC81A',
    borderWidth: 2,
    width: 319,
    height: 50,
    color:'black',
  },
  label: {
    marginBottom: 10,
    marginLeft: 25,
    alignSelf: 'flex-start',
    color: '#C4C4C4',
  },
  subHeaderText: {
    fontSize: 12,
    color: '#C4C4C4',
    alignSelf: 'flex-end',
    fontWeight: '500',
    lineHeight: 18,
    marginVertical: 9,
    marginRight: 25,
  },
  btn: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#EFC81A',
    padding: 10,
    borderRadius: 15,
    width: 183,
    height: 50,
    marginBottom: 18,
  },
  btnlabel: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 24,
    color: 'white',
    alignSelf: 'center',
  },
  shadow: {
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 50,
  },
});
